---
- name: Bonus Lesson 2.4 - Testing a simple custom module
  hosts: local
  tasks:
    - name: Test new module
      simple_custom_module:
        my_str: 'convert to upper case'
      register: return_value

    - name: Print output to stdout
      ansible.builtin.debug:
        var: return_value

 
