---
- name: Bonus Lesson 2.5 - Testing a complex custom module
  hosts: cisco1
  tasks:
    - name: Test new module
      complex_custom_module:
        host: "{{ ansible_host }}"
        device_type: cisco_ios
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        config_list:
          - logging buffered 20000
          - no logging console

    - name: Verify configuration changes were made
      cisco.ios.ios_command:
        commands: show run | inc logging
      register: sh_log

    - name: Print output of verify commmand to stdout
      ansible.builtin.debug:
        var: sh_log

 
