---
- name: Exercise 8.1 - Use TextFSM to create a list and then combine into a dictionary
  hosts: nxos
  gather_facts: False
  vars:
    platform: "cisco_nxos"
    command: show lldp neighbors 
    textfsm_index: "/home/wbellward/ntc-templates/ntc_templates/templates/"
  tasks:
    - name: Retrieve results from 'show lldp neighbor' command
      cisco.nxos.nxos_command:
        commands: "{{ command }}"
      register: output

    - name: Use TextFSM to parse 'show lldp neighbors'
      ansible.builtin.set_fact:
        sh_lldp: "{{ output.stdout[0] | ntc_parse(command, platform, textfsm_index) }}"

    - name: Print parsed output
      ansible.builtin.debug:
        var: sh_lldp

    - name: Create a dictionary with 'local_intf' as the key and 'remote_dev' as value
      ansible.builtin.set_fact:
        lldp_dict: "{{ lldp_dict | default({}) | combine({item['local_interface']: item['neighbor']}) }}"
      loop: "{{ sh_lldp }}"
      loop_control:
        label: ""

    - name: Print 'lldp_dict' as final output
      ansible.builtin.debug:
        var: lldp_dict
 
