---
- name: OS Upgrade on Cisco IOS-XE devices
  hosts: do_not_run_this_playbook
  gather_facts: True

  roles:
    - upgrade_pre_process
    - transfer_image
    - upgrade_device
    - upgrade_post_process

