- name: Update to boot settings to use new image file
  ansible.builtin.import_tasks: update_bootsystem.yml
  tags: bootsystem

- name: Reload the device
  ansible.builtin.import_tasks: reload_device.yml
  tags: reload
  
