---
- name: Exercise 6.2b - Use 'import_task' to print each item in loop
  hosts: local
  gather_facts: False
  vars:
    alt_tasks: subtask1.yml
  tasks:
    - name: Runtime import
      # ansible.builtin.import_tasks: "{{ subtask1 }}"
      ansible.builtin.import_tasks: "{{ alt_tasks }}"

