---
- name: Exercise 3.1 - Conditionals, Tags and Limits
  hosts: arista:cisco:juniper
  gather_facts: False
  tasks:

    - name: Retrieve "show ip arp" when "ansible_network_os" is eos
      arista.eos.eos_command:
        commands:
          - sh ip arp
      register: sh_ip_arp_eos
      tags: eos
      when: ansible_network_os == "eos"

    - name: Retrieve "show ip arp" when "ansible_network_os" is ios
      cisco.ios.ios_command:
        commands:
          - sh ip arp
      register: sh_ip_arp_ios
      tags: ios
      when: ansible_network_os == "ios"

    - name: Retrieve "show arp" when "ansible_network_os" is junos
      junipernetworks.junos.junos_command:
        commands:
          - sh arp
      register: sh_arp_junos
      tags: junos
      when: ansible_network_os == "junos"

    - name: Print only the "sh_ip_arp_eos" varible to stdout
      ansible.builtin.debug:
        var: sh_ip_arp_eos
      #when: sh_ip_arp_eos is defined
      when: ansible_network_os == "eos" 

 
