- name: Select the file-system to use.
  ansible.builtin.set_fact:
    dest_filesystem: "{{ ansible_facts.net_filesystems[0] }}"

- name: Display the file-system selected.
  ansible.builtin.debug:
    var: dest_filesystem

- name: Verify file_system is allowed.
  ansible.builtin.assert:
    that:
      - dest_filesystem in allowed_filesystems
    success_msg: "Using file-system: {{ dest_filesystem }}"

