- name: Destination PATH
  ansible.builtin.debug:
    msg: "{{ dest_filesystem }}/{{ primary_image.name }}"

- name: Transfer image file
  vars:
    # Transfer takes forever and a half
    ansible_command_timeout: 21600
  ansible.netcommon.net_put:
    src: "{{ primary_image.name }}"
    dest: "{{ dest_filesystem }}/{{ primary_image.name }}"
    protocol: scp
  when: ansible_facts.net_model == "C1111-4P"

