- name: Perform MD5 (returns 'md5_hash' variable)
  ansible.builtin.import_role:
    name: file_operations
    tasks_from: md5

- name: Verify remote MD5 is correct
  ansible.builtin.assert:
    that:
      - md5_hash == primary_image.md5
    fail_msg: "MD5-hash on remote device is not correct {{ md5_hash }} != {{ primary_image.md5 }}"
    success_msg: "MD5-hash on remote device is correct!"

