---
- name: Exercise 5.4 - Use 'nxos_config' to deploy configs from exercise 3
  hosts: nxos1:nxos2
  gather_facts: False
  tasks:
    - name: Configure Interface and BGP using config files
      cisco.nxos.nxos_config:
        src: "configs/{{ inventory_hostname }}-final-config.txt"

    - name: Verify that the new BGP peers are established
      cisco.nxos.nxos_command:
        commands: show ip bgp summary
      register: sh_bgp

    - name: Print out the BGP summary
      ansible.builtin.debug:
        var: sh_bgp.stdout_lines[0]

