---

- name: Exercise6e - All errors resolved
  hosts: juniper
  gather_facts: False

  tasks:
    - name: Executing command
      junipernetworks.junos.junos_command:
        commands: show interfaces terse
      register: output

    - ansible.builtin.debug:
        msg: "{{ output }}"

