---
- name: Exercise 2.1 - Modules and Fact Gatering 
  hosts: arista5
  gather_facts: True
  tasks:
    - name: All Ansible facts to stdout
      ansible.builtin.debug: 
        var: ansible_facts

    - name: All ipv4 addresses to stdout
      ansible.builtin.debug: 
        var: ansible_facts.net_all_ipv4_addresses

