---
- name: Exercise 6.6 - Use 'roles' to config devices
  hosts: cisco5:cisco6
  gather_facts: False
    # The following roles all do the same thing except 'vrf-alt1 & 2' are not
    # idempotent and vrf-alt2 offers some good debugging
  roles:
    - vrf
    #- vrf-alt1
    #- vrf-alt2

