---
- name: Exercise 3.5 - Pulling in varibles and assembling config parts
  hosts: nxos
  gather_facts: False
  vars_files:
    - group_vars/nxos/bgp.yml
  tasks:
    - name: Create BGP Configuration File
      ansible.builtin.template:
        src: ex3_5_nxos_bgp.j2
        # Prefix the filename with a number to ensure assemble in that order
        dest: "configs/{{ inventory_hostname }}/02-{{ inventory_hostname }}-bgp.txt"

    - name: Create Interface Configuration File
      ansible.builtin.template:
        src: ex3_5_nxos_interfaces.j2
        # Prefix the filename with a number to ensure assemble in that order
        dest: "configs/{{ inventory_hostname }}/01-{{ inventory_hostname }}-intf.txt"

    - name: Combine/assemble previously generated files into one file
      ansible.builtin.assemble:
        src: "./configs/{{ inventory_hostname }}/"
        dest: "./configs/{{ inventory_hostname }}-final-config.txt"
