---
- name: Exercise 6.1b - Use 'include_task' to print each item in loop
  hosts: local
  gather_facts: False
  tasks:
    - name: Runtime include
      ansible.builtin.include_tasks: "{{ subtask1 }}"
      loop:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.1.3
        - 10.1.1.4

