---
- name: Exercise 6.1c - Use 'include_task' to print three messages with tags
  hosts: local
  gather_facts: False
  tasks:
    - name: Runtime include
      ansible.builtin.include_tasks: subtask2.yml

    - name: Tags and include (exercise1c-fix1)
      ansible.builtin.include_tasks: subtask2.yml
      tags:
        - msg1
        - msg2
        - msg3
   
    - name: Tags and include (exercise1c-fix2)
      ansible.builtin.include_tasks: subtask2.yml
      tags: always
