- name: Configure DNS on Cisco NXOS 
  cisco.nxos.nxos_config:
    lines:
      - "ip name-server {{ dns_server1 }} {{ dns_server2 }} "
      - "ntp server {{ ntp_server1 }} use-vrf management"
      - "ntp server {{ ntp_server2 }} use-vrf management"
      - "ip domain-name {{ domain_name }}"

